# Generated by Django 2.1 on 2019-12-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_at', models.DateTimeField(auto_now_add=True)),
                ('work_type', models.CharField(default='N', max_length=1, verbose_name='타입')),
            ],
        ),
    ]
