# Generated by Django 2.1 on 2019-12-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_history',
            new_name='WorkHistory',
        ),
    ]
