# Generated by Django 2.1 on 2019-12-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191202_0532'),
        ('work', '0002_auto_20191202_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='accounts.Profile'),
        ),
    ]
