# Generated by Django 2.1 on 2019-12-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='used_status',
            field=models.CharField(default='N', max_length=1, verbose_name='사용중여부'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='remained_time',
            field=models.IntegerField(verbose_name='잔여시간(분)'),
        ),
    ]
